### PR TITLE
reorder code

### PR DESCRIPTION
**Pull request by arnetheduck**
declare checkpoint/fail before use to avoid random compile errors

### CODE REVIEW

**Comment by stefantalpalaru** [comment]
Interesting that the CI "push" event used an older version of ".github/workflows/ci.yml" while the "pull-request" event used the new one.

**Comment by arnetheduck** [comment]
I probably based it off some old commit

**Comment by stefantalpalaru** [comment]
That would have manifested in the diff.

**Comment by arnetheduck** [comment]
not really, github/git is smart enough to figure it out and show diff against the merge base

**Pull request merged**
